.TH DECAESER "6" "June 2025" "decaeser v1.0.0" "Games Manual"
.SH NAME
decaeser \- brute-force a caeser cipher
.SH SYNOPSIS
.B decaeser
[\fI\,OPTION\/\fR]... [\fI\,FILE\/\fR]
.SH DESCRIPTION
Brute-force the decryption of caeser shift ciphers.
.PP
With no FILE, or when FILE is -, read standard input.
.SH BUGS
This program is very slow.
The characterset mode attack will be defeated by any character ordering that is not that provided by Python, or any set order that is not Upper-Lower-Digit-Punctuation-Whitespace.
.SH COPYRIGHT
.SH COPYRIGHT
Copyright (C) 2025 Jack Renton Uteg.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH SEE ALSO
\fBcaeser(6)\fR
