.TH DECAESER "6" "June 2025" "decaeser v1.0.0" "Games Manual"
.SH NAME
decaeser \- brute-force a caeser cipher
.SH SYNOPSIS
.B decaeser
[\fI\,OPTION\/\fR]... [\fI\,FILE\/\fR]
.SH DESCRIPTION
Brute-force the decryption of caeser shift ciphers.
.PP
With no FILE, or when FILE is -, read standard input.
.SH BUGS
This program is very slow.
The characterset mode attack will be defeated by any character ordering that is not that provided by Python, or any set order that is not Upper-Lower-Digit-Punctuation-Whitespace.
.SH COPYRIGHT
Copyright C Jack Renton Uteg 2025
.SH SEE ALSO
\fBcaeser(6)\fR
